### ISSUE TITLE
Code currently broken on PHP 7

### ISSUE THREAD

**Issue by pcdog** [hsdn/lg#1]
PHP Parse error:  syntax error, unexpected '}', expecting end of file in /opt/lg/htdocs/index.php on line 515

PHP 7.0.7-1+donate.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

**Comment by justkeepquiet** [comment]
On php 7 code is not tested, there is no possibility to test now. On php 5.4 works fine.

**Comment by rendragnet** [comment]
Hmm, it's actually not a php7 issue.  I have seen it working on php7 on a cpanel server.

However on non-cpanel, the code doesn't work on php7.1, php5.4 or php5.6, all with the same error:
damien@echelon:~$ curl https://raw.githubusercontent.com/hsdn/lg/master/htdocs/index.php > index2.php
damien@echelon:~$ php index2.php 
PHP Parse error:  syntax error, unexpected '}' in /home/damien/index2.php on line 515
damien@echelon:~$ php -v
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 14 2016 13:13:28) 

Same issue on 5.4.45:
[root@lg dev]# php -v
PHP 5.4.45 (cli) (built: Feb 18 2017 15:55:26) 

Any thoughts?

**Comment by rendragnet** [comment]
Found it!

There's three malformed php open tags which need to be fixed.

Lines 212, 570, 582

Then it works on a standard modern PHP install :)

**Comment by justkeepquiet** [comment]
Hello.

This problem is not associated with the version of php, but with the value of the "short_open_tag" parameter in php.ini. At our server it in value "1", therefore the error was not detected. Sorry.

It is fixed now. Thanks for contribution.
