### ISSUE TITLE
Support for vender Huawei 

### ISSUE THREAD

**Issue by eric9309** [hsdn/lg#11]
Hi, any chance of adding support for Huawei routers (comware) ?

**Comment by justkeepquiet** [comment]
Hello, in the near future - no. I do not have Huawei router for script development and testing.

**Comment by eric9309** [comment]
[Hauwei-array-hg.txt](https://github.com/hsdn/lg/files/1855980/Hauwei-array-hg.txt)

Hi, the hp comware vm HP VSR1001  you can get for free to test, the comands are the same, except that they have ipv4 after the routing-table commmand "display bgp routing-table ipv4"

**Comment by justkeepquiet** [comment]
Thanks for the info. I look in the near future.

**Comment by justkeepquiet** [comment]
Partial support for Huawei and openbgpd commands (without parsers) is added by pull request https://github.com/hsdn/lg/pull/15.
