### ISSUE TITLE
ROS 6.42.1 not working

### ISSUE THREAD

**Issue by raxxy** [hsdn/lg#13]
Hey mate,

trying to set this up on ROS 6.42.1 and it doesn't appear to be working, any ideas?

Just getting login failed each time, but wireshark and the router are both reporting login, wireshark trace shows connection and then it just quits.

**Comment by felipeandrade55** [comment]
Hello, I'm having the same problem. When running any command I have the error "Telnet error: Login failed." But following the LOG of the router I realize that it is logged in and then logout. Any solution for this case?

**Comment by justkeepquiet** [comment]
Hi, this problem now fixed https://github.com/hsdn/lg/commit/05dc8fc6baeec06d3f9f74be098c374f933dc2a4. Please update.
