### ISSUE TITLE
show ip bgp neighbors IOS-XR

### ISSUE THREAD

**Issue by bape-b** [hsdn/lg#14]
In the show ip bgp neighbors command in IOS-XR, the response does not match the neighbor's IP address.
In IOS it is followed by a comma, not in IOX-XR.

`--- index.php	2018-04-24 15:12:36.000000000 -0300`
`+++ index.php.orig	2018-01-08 16:53:19.000000000 -0300`
`@@ -565,11 +565,8 @@`
` 					}`
` 				}`
` 			}`
`-/*`
`-*			if ($fp = @popen('echo n | '.$_CONFIG['plink'].' '.implode(' ', $params).' '.$exec, 'r'))`
`-*/`
` `
`-			if ($fp = @popen($_CONFIG['plink'].' '.implode(' ', $params).' 0>&1 '.$exec, 'r'))`
`+			if ($fp = @popen('echo n | '.$_CONFIG['plink'].' '.implode(' ', $params).' '.$exec, 'r'))`
` 			{`
` 				while (!feof($fp))`
` 				{`
`@@ -1454,7 +1450,7 @@`
` 	if (preg_match("/^show ip bgp n\w*\s+([\d\.]+)/i", $exec) OR`
` 			 preg_match("/^show ip bgp n\w*$/i", $exec))`
` 	{`
`-		if (!isset($lastip) AND preg_match("/^BGP neighbor is ([\d\.]+)(,?)/", $output, $lastip_exp))`
`+		if (!isset($lastip) AND preg_match("/^BGP neighbor is ([\d\.]+),/", $output, $lastip_exp))`
` 		{`
` 			$lastip = $lastip_exp[1];`
` 		}`
`@@ -1518,7 +1514,7 @@`
` 			$output`
` 		);`
` 		$output = preg_replace_callback(`
`-                      "/^(BGP neighbor is )(\d+\.\d+\.\d+\.\d+)(,?)/",`
`+			"/^(BGP neighbor is )(\d+\.\d+\.\d+\.\d+)(,)/",`
` 			function ($matches) {`
` 				return $matches[1].link_whois($matches[2]).$matches[3];`
` 			},`

[lg.txt](https://github.com/hsdn/lg/files/1944159/lg.txt)

**Comment by justkeepquiet** [comment]
Accepted. But some versions do not work without `echo n |` , so this changes needs to be checked in practice.

**Comment by MedH27Y** [comment]
Hi hsdn, bape-b

@bape-b, you are the only one who talk about looking glass in IOS-XR, I tried everything, i can't connect to my router by ssh or telnet, I always had "Command failed", and wen i check in the log, sometimes i had "Connection closed by peer or reset by peer" and what's good, sometimes i got the banner login of my router in the log error ! 
I'm little confused, please advise !
@hsdn , your help is always welcome !
