### ISSUE TITLE
Double <html> in object data

### ISSUE THREAD

**Issue by Nousin** [hsdn/lg#16]
Hello! First, I wanted to congratulate you on your work and thank you.
Can you help me with this doubt?
When I generate the graph, it creates an additional html, which causes the graph to get stuck in a "box"

https://uploaddeimagens.com.br/imagens/lg1-png-b2ab3993-51ec-4469-8267-6d69d4d8f1e5
https://uploaddeimagens.com.br/imagens/lg2-png

once again
Thank you!

**Comment by justkeepquiet** [comment]
Hi, please read https://github.com/hsdn/lg/issues/8, this is same problem (with version of php).

**Comment by Nousin** [comment]
Hello!
I tried auto remove my php with version 7.0.
Try with 5, but I did not get results.

What caught my attention is that it generates a frame with a second html stage graph, and the examples already create <svg>

![image](https://user-images.githubusercontent.com/41834853/43378341-aaab0c1a-939c-11e8-9cac-d8367f611777.png)

![image](https://user-images.githubusercontent.com/41834853/43378360-c438fd40-939c-11e8-9ced-75f1463f78e7.png)

**Comment by justkeepquiet** [comment]
Hi, 
the LG script does not generates html code. This code fully generates by Graphviz library (installed on your server), probably the problem is there. Also, the problem can be in a web-server software or php.

We tested our script on php 5.3, 5.5 and 7.0 (CentOS 7), there is no problems.

**Comment by Nousin** [comment]
Oh right.
Thank you very much for your support, I will look further into the problem.

Congratulations on work!

**Comment by justkeepquiet** [comment]
Thanks for your interest. If you find a way to solve the problem, please tell us.
