### ISSUE TITLE
Huawei Router Filter

### ISSUE THREAD

**Issue by leandrosnn** [hsdn/lg#18]
Hi everyone, Can anyone help me with Huawei router filter, I need to perform the following filter, to rertornar only some information display bgp routing-table 8.8.8.8 | AS-path | Community | Duration | From | BGP

'huawei' => array
(
	'ipv4' => array
	(
		'bgp' => 'display bgp routing-table %s ',
		'advertised-routes'	=> 'display bgp routing-table peer %s advertised-routes',
		'received-routes' => 'display bgp routing-table peer %s received-routes',
		'routes'	=> 'display bgp routing-table peer %s received-routes active',
		'summary' => 'display bgp peer',
		'ping' => 'ping  %s',
		'trace' => 'tracert  %s',
	),
	'ipv6' => array
	(
		'bgp' => 'display bgp ipv6 routing-table %s',
		'advertised-routes' => 'display bgp ipv6 routing-table peer %s advertised-routes',
		'received-routes' => 'display bgp ipv6 routing-table peer %s received-routes',
		'routes'	=> 'display bgp ipv6 routing-table peer %s received-routes active',
		'summary' => 'display bgp ipv6 peer',
		'ping' => 'ping ipv6 %s',
		'trace' => 'tracert ipv6 %s',
	)
),

**Comment by justkeepquiet** [comment]
Sorry, where is problem? You can change the format of the command in the index.php file.

**Comment by leandrosnn** [comment]
Hello! Actually I need help in order to filter the command lines, where you can filter some information about the command output.

For example:

'bgp' => 'display bgp routing-table% s',

I need to add the following after% s | AS-path | Community | Duration | From | BGP

But I'm not getting this filter, could you help me

![image](https://user-images.githubusercontent.com/44237236/47272786-e035d080-d560-11e8-8582-b9415fb417ba.png)

**Comment by justkeepquiet** [comment]
I do not know how filters work in Huawei. And the LG script also have no such this features.

**Comment by leandrosnn** [comment]
The filters of the router huawei I know do, just do not know how PHP can perform the translation as picture below presents an error.

![image](https://user-images.githubusercontent.com/44237236/47279761-742b8a80-d5a9-11e8-8d3a-eda782cfdbc1.png)

**Comment by justkeepquiet** [comment]
About the character "|" - this character automatic replaced with "\\|" by escapeshellcmd() function (this is a security issue). Perhaps the problem is this.

**Comment by justkeepquiet** [comment]
We have made changes to the script. That should work. Please update and test.

**Comment by rguaitanele** [comment]
Try this 
display bgp routing-table 8.8.8.8 | include (AS-path|Community|Duration|From|BGP)

**Comment by leandrosnn** [comment]
Hello @hsdn , the filter is working properly, thank you very much for your help, so that users of equipment Huawei NE40, could make the necessary filters to return only useful information.

Regards,

Leandro Santos
