### ISSUE TITLE
BGP GRAPH 

### ISSUE THREAD

**Issue by leandrosnn** [hsdn/lg#19]
Hi everyone, could you help me with BGP GRAPH, do not return image

![image](https://user-images.githubusercontent.com/44237236/47260648-d2ffdf80-d495-11e8-8c3b-1560ea6cf1d8.png)

**Comment by justkeepquiet** [comment]
You need to install the **GraphViz** software. This software is required for Image_GraphViz php library.
See https://graphviz.gitlab.io/download/

**Comment by justkeepquiet** [comment]
Also, for testing functionality of the Image_GraphViz library, please use this php script:
```php
<?php
error_reporting(E_ERROR);
include 'Image/GraphViz.php';
$graph = new Image_GraphViz();
$graph->addNode('test', array(
	'label' => 'The Image_GraphViz is worked!',
	'shape' => 'none',
	'fontcolor' => 'green', 
	'fontsize' => 14
));
$graph->image('svg');
?>
```

**Comment by leandrosnn** [comment]
Hi, I'm using the Windowns 7 operating system, and I already installed the software https://graphviz.gitlab.io/download/, but I do not know how to start it.

**Comment by leandrosnn** [comment]
I did the test but did not return the image either

![image](https://user-images.githubusercontent.com/44237236/47260898-5d4a4280-d49a-11e8-9717-3ecb2d7f3739.png)

**Comment by leandrosnn** [comment]
Is the path on the network correct where I put the Image_GraphViz-1.3.0 file?

![image](https://user-images.githubusercontent.com/44237236/47261030-e498b580-d49c-11e8-98e8-9b093cd5e0bc.png)

![image](https://user-images.githubusercontent.com/44237236/47261032-fc703980-d49c-11e8-8523-99b90b5a151d.png)

**Comment by justkeepquiet** [comment]
Location of GraphViz.php is correct. A "blank screen" indicates that Image_GraphViz library cannot execute GraphViz program. We do not known how to fix it and we not tested this library on Windows.

**Comment by justkeepquiet** [comment]
The Image_GraphViz library is designed for Unix-like operating systems, and most likely does not work on the Windows.

**Comment by leandrosnn** [comment]
I understood, thanks for your help, Can you help me with # 18 ?
