### ISSUE TITLE
Mikrotik Telnet Issue

### ISSUE THREAD

**Issue by hostlinkau** [hsdn/lg#2]
Hi

When using Mikrotik to login to our routers via this script, we see in the log that the user logs in/out within a matter of a second, and the page returns

Telnet error: Login failed.

As i said, the user logs in and out straight away  we can verify this in the log

Please help with this issue.

Daniel

**Comment by justkeepquiet** [comment]
Hello,

What is OS version on your router?
We tried connect to the router (via telnet program) from the server where the LG script is placed?

**Comment by hostlinkau** [comment]
Hi

Sorry for the delayed response.

Our router is running 6.39.1

You can view this at http://lg.hostlink.com.au/dev/

If you dont mind, can you add me on skype to further diagnose this?  glo-daniel is my username

Regards
Daniel

**Comment by justkeepquiet** [comment]
Sorry, there are no details on the problem yet. In the near future we will check on our equipment this issue.

**Comment by justkeepquiet** [comment]
Problem "Telnet error: Login failed" on ROS 6.39+
Fixed https://github.com/hsdn/lg/commit/05dc8fc6baeec06d3f9f74be098c374f933dc2a4
