### ISSUE TITLE
Screen-length 0 temporary - Huawei

### ISSUE THREAD

**Issue by leandrosnn** [hsdn/lg#21]
Hi everyone, I need to enter the command (screen-length 0 temporary) before the Huawei router commands. display without any breaks

![image](https://user-images.githubusercontent.com/44237236/47707279-38786c80-dc0a-11e8-9d59-2a5108e6b899.png)

http://support.huawei.com/hedex/pages/EDOC100009448831188717/02/EDOC100009448831188717/02/resources/vrp/screen-length_temporary.html

**Comment by justkeepquiet** [comment]
Hi, if you use SSH, try add this lines:
```php
// Huawei disable screen breaks
if ($os == 'huawei')
{
	@shell_exec('echo n | '.$ssh_path.' '.implode(' ', $params).' screen-length 0 temporary');
}
```
bfore this:
```php
if ($fp = @popen('echo n | '.$ssh_path.' '.implode(' ', $params).' '.$exec, 'r'))
```

And, if you use Telnet, add this lines:
```php
// Huawei disable screen breaks
if ($os == 'huawei')
{
	$telnet->write('screen-length 0 temporary');
}
```
before this:
```php
$telnet->write(($os == 'junos') ? $exec.' | no-more' : $exec);
```

**Comment by justkeepquiet** [comment]
Please test this solutions. If it working ok, we will add changes to the script.

**Comment by leandrosnn** [comment]
Hello I will perform new tests today and I will return.

**Comment by leandrosnn** [comment]
Hi Dmitry Shin, I ran the tests as requested, and it worked perfectly for the commands, (bgp advertised-routes, bgp summary), but for the output of the command (bgp) it is not returning the complete result of the available routes, as below .

![image](https://user-images.githubusercontent.com/44237236/47824791-47b40300-dd4d-11e8-8d0f-9eb4fb7f5a8f.png)

Can you help me

**Comment by justkeepquiet** [comment]
Hi, we need access to the router for testing.

**Comment by leandrosnn** [comment]
Hello @hsdn Could you inform me your email to contact!

**Comment by justkeepquiet** [comment]
dmitry.s@hsdn.org

**Comment by leandrosnn** [comment]
Thanks @hsdn Dmitry! I sent you the email now.

**Comment by thiagoe** [comment]
Same problem here, tried uncomment lines about terminal length but this dont work, any suggestion?
