### ISSUE TITLE
Support for VYOS

### ISSUE THREAD

**Issue by dgwatson1988** [hsdn/lg#22]
Hi Guys

I was wondering if its possible for you to add support for VYOS?
We are currently using Mikrotik but looking at deploying new locations with VYOS

Cheers
D

**Comment by justkeepquiet** [comment]
Hi, at the moment it is not planned, because we have no VyOS equipment for testing.

**Comment by dgwatson1988** [comment]
Hi Dmitry

 

If I supplied you with a VYOS router for testing,  do you think you could incorporate this for me?

 

Cheers

**Comment by dgwatson1988** [comment]
Hi Dmitry



If I supplied you with a VYOS router for testing,  do you think you could incorporate this for me?



Cheers

**Comment by justkeepquiet** [comment]
If I have time, we will try to discuss this issue.
