### ISSUE TITLE
Install GraphViz tools on CentOS 7/cPanel

### ISSUE THREAD

**Issue by yapjackson** [hsdn/lg#25]
Hi,
We have upgraded from CentOS 6 to 7. But now, it seems even though GraphViz tools is installed.

Anyone has working instructions how to install GraphViz tools on CentOS 7? Take note NOT Perl Image_GraphViz as that was installed.

**Comment by yapjackson** [comment]
Still can't find any GraphViz repo for CentOS 7. :(

**Comment by yapjackson** [comment]
this project seems like dead :(

**Comment by justkeepquiet** [comment]
Hi,
The project is not dead.

When installing on CentOS 7 I did not have any problems. 

To install GraphViz package use command:
`yum install graphviz`

To install php Pear package for GraphViz use commands:
`pear install Image_GraphViz`
or
`yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
`yum install php-pear-Image-GraphViz`

For more info, please see:
https://fedoraproject.org/wiki/EPEL
https://centos.pkgs.org/7/centos-x86_64/graphviz-2.30.1-21.el7.x86_64.rpm.html
https://centos.pkgs.org/7/epel-x86_64/php-pear-Image-GraphViz-1.3.0-7.el7.noarch.rpm.html

**Comment by yapjackson** [comment]
Hi!

But yum update only provide the old graphviz version, which couldn't work as we know we need newer version like 2.4 above for the graph to work properly?

 graphviz          x86_64          2.30.1-21.el7

**Comment by justkeepquiet** [comment]
We use version 2.30.1-21.el7 on our lg server. This version is exists in CentOS standard repo.

```
[root@server ~]# yum list | grep graphviz
graphviz.x86_64                            2.30.1-21.el7              @base
graphviz.i686                              2.30.1-21.el7              base
...

[root@server ~]# pear list | grep GraphViz
Image_GraphViz   1.3.0   stable
```

**Comment by yapjackson** [comment]
Yes,
everything is the same. But the graph is showing empty. Any logs we can check?

**Comment by justkeepquiet** [comment]
Probably php does not have permission to run the graphviz command. Try to run php script from the root user.

**Comment by yapjackson** [comment]
Unfortunately we still got no idea, no PHP error is showing, just no graph.
Any way we can get the error output to anywhere?

**Comment by justkeepquiet** [comment]
If there is no permission to execute the command, the error is not displayed.

**Comment by yapjackson** [comment]
Hi, can you advice what command CLI can we run to test the graph?

**Comment by justkeepquiet** [comment]
You can use this script https://github.com/hsdn/lg/issues/6#issuecomment-354226734 for tests with CLI.

**Comment by yapjackson** [comment]
Yes it is showing blank. I think the issue is "GraphViz toolkit" is not installed.

But it is not available for centos 7 on graphviz.org . I remembered previously they have and they removed it. The last one provided was for centos 6. Do you have any advice?

**Comment by yapjackson** [comment]
running as root it shows successful test. Let me test further.

**Comment by yapjackson** [comment]
I run the graphviz_test.php as root from CLI, it works.
I then tried changing the php file to root, apache and even nobody. but none of them works. The page shows empty still.
Do you have any advice? :O

**Comment by justkeepquiet** [comment]
Check open_basedir parameter in your php.ini or VirtualHost configuration. You need provide access to graphviz binary or disable open_basedir.

Example of VirtualHost configuration:
```
php_admin_value open_basedir none
```

**Comment by yapjackson** [comment]
Thanks hsdn. Unfortunately all the values are set to none. The most frustrating is we cannot see any error thrown by the php. I will try abit more if still can't we will just leave it without the graph. Thanks again!

**Comment by tryhardtheis** [comment]
hi, does this application support mikrotik os version 6.44.6  ?
