### ISSUE TITLE
Telnet / ssh connection failed with IOS XR

### ISSUE THREAD

**Issue by kalypso49** [hsdn/lg#26]
Hello, I can't connect with a IOS XR router, i have a "connection failed' with telnet and a "command failed" with ssh.
I test the looking glass with a router IOS and it works
Can you advice me please

**Comment by justkeepquiet** [comment]
Hi, you use plink or sshpass? Sorry, but we not tested script with IOS XR.

**Comment by kalypso49** [comment]
I use sshpass, I also tried to connect with ssh and telnet from my server and it didn't work
