### ISSUE TITLE
Incomplete response in Huawei NE

### ISSUE THREAD

**Issue by broonu** [hsdn/lg#31]
Hello,

We're trying this with Huawei routers and see that the looking-glass response is incomplete compared to the same command inside the router itself.
Below is the different replies with a NE40E-X8 router.

Command executed inside router:
```
<HUAWEI1>display bgp routing-table A.A.A.A
 BGP local router ID : 10.29.0.253
 Local AS number : ASAAAAA
 Paths:   1 available, 1 best, 1 select
 BGP routing table entry information of A.A.A.A/24:
 From: B.B.B.B (C.C.C.C)
 Route Duration: 1d01h08m24s
 Direct Out-interface: Eth-Trunk1.3682
 Original nexthop: B.B.B.B
 Qos information : 0x0
 Community:<ASAAAAA:12417>, <ASAAAAA:25400>, <ASAAAAA:24400>, <ASAAAAA:23400>
 AS-path ASBBBBB, origin igp, localpref 200, pref-val 0, valid, external, best, select, active, pre 255
 Advertised to such 5 peers:
    A.A.A.236
    A.A.A.252
    A.A.A.247
    A.A.A.84
    A.A.A.81

```
Reply from looking-glass webpage:
```
Command: display bgp routing-table A.A.A.A
 BGP local router ID : 10.29.0.253
 Local AS number : ASAAAAA
 Paths:   1 available, 1 best, 1 select
 BGP routing table entry information of A.A.A.A/24:
 From: B.B.B.B (C.C.C.C)
 Route Duration: 1d01h10m09s 
 Direct Out-interface: Eth-Trunk1.3682
 Original nexthop: B.B.B.B
 Qos information : 0x0
```

**Comment by thiagoe** [comment]
Same problem here, tried uncomment lines about terminal length but this dont work.

**Comment by thiagoe** [comment]
Solution temporary, in terminal of NE use comand 
# screen-length 0
https://support.huawei.com/enterprise/en/doc/EDOC1100064353/2725413f/screen-length

after this all work.

**Comment by broonu** [comment]
> Solution temporary, in terminal of NE use comand
> 
> # screen-length 0
> https://support.huawei.com/enterprise/en/doc/EDOC1100064353/2725413f/screen-length
> 
> after this all work.

This feature is just available for:

3: Management level (user interface view)
0: Visit level (user view)

Level 0 can't even show BGP sessions and I don't think a level 3 account is a good ideia for security reasons.

**Comment by makanbaks0-zz** [comment]
hi.. 
I just got no result of command, it only showed halfway, tried it with and without screen-length 0 same result.

any solution?
thanks.

```
Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 2.
      The current login time is 2020-10-09 10:00:58.
  PING 10.x.x.x: 56  data bytes, press CTRL_C to break
```
