### ISSUE TITLE
Traceroute on 6.39.2 not Working

### ISSUE THREAD

**Issue by fupsi42** [hsdn/lg#4]
Hi,

traceroute to my MikroTik is not working.
I get the error message:
`expected end of command (line 1 column 43)`
Ping and BGP informations are working.

Hope you can help me!

Br
Markus

**Comment by Pinkbyte** [comment]
Try to remove 'count=1' from Mikrotik's traceroute command section in index.php.
Not sure if it will break older versions of Mikrotik, though!

**Comment by justkeepquiet** [comment]
If it works, please report. I'll make changes to the code. Thanks.

**Comment by bhillebrand-enee** [comment]
Hey there! Had the same issue on v6.40.4

Adding an echo $exec; line right before the command is processed seems to indicate that the count=1 line is being added to the command twice for some reason. **IE: /tool traceroute 8.8.8.8 **count=1** size=56 **count=1****

The two occurrences of count are coming from lines 255 and 624, resulting the command to fail. Removing the redundant instance of count resolves the issue.

**Comment by Guigui37** [comment]
Hey,
You are right about removing count=1, but you see latency in ms in your result ? Not me...
For exemple, I see this:
 5 google-public-dns-a.google.com (8.8.8.8) [AS AS15169] ms ms ms

**Comment by Guigui37** [comment]
Nobody have an idea about this ?

**Comment by Guigui37** [comment]
Solved with last updates.
