### ISSUE TITLE
PHP5.6 Fatal Error on line 1314

### ISSUE THREAD

**Issue by GizmoV** [hsdn/lg#7]
NGINX:

2017/12/22 00:17:17 [error] 2989#0: *1 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '80.81' (T_DNUMBER) in /var/www/html/index.php(1314) : regexp code on line 1
PHP message: PHP Fatal error:  preg_replace(): Failed evaluating code:
&quot; &quot;.link_command(&quot;bgp&quot;, &quot;neighbors+&quot;80.81.192.6&quot;+routes+all&quot;, &quot;Import&quot;).&quot;: &quot; in /var/www/html/index.php on line 1314" while reading upstream, client: 10.22.15.2, server: lg.cln.net, request: "GET /?router=Jun0-MR&protocol=ipv4&command=bgp&query=neighbors+80.81.192.6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "lg.cln.net", referrer: "http://lg.cln.net/?command=summary&protocol=ipv4&query=&router=Jun0-MR"

Apache:

[Thu Dec 21 23:42:44.648685 2017] [:error] [pid 583] [client 10.22.15.2:49342] PHP Parse error:  syntax error, unexpected '78.25' (T_DNUMBER) in /var/www/html/index.php(1314) : regexp code on line 1, referer: http://lg.cln.net/?command=summary&protocol=ipv4&query=&router=Jun0-MR
[Thu Dec 21 23:42:44.648751 2017] [:error] [pid 583] [client 10.22.15.2:49342] PHP Fatal error:  preg_replace(): Failed evaluating code: \n&quot; &quot;.link_command(&quot;bgp&quot;, &quot;neighbors+&quot;78.25.75.133&quot;+routes+all&quot;, &quot;Import&quot;).&quot;: &quot; in /var/www/html/index.php on line 1314, referer: http://lg.cln.net/?command=summary&protocol=ipv4&query=&router=Jun0-MR

**Comment by justkeepquiet** [comment]
Hi,

What version of PHP?

**Comment by GizmoV** [comment]
5.6.30

**Comment by justkeepquiet** [comment]
By the link in your log the command is executed. Probably, the error is related to parsing output. I will try to rewrite the code in the near future with **preg_replace_callback**, this will probably solve the problem.

We tested the code on php 5.4.16 on our lg server, there was no error.

**Comment by GizmoV** [comment]
Thank you for your work! I look forward to the hotfix.
This script is very useful by transit telecom operators.

**Comment by justkeepquiet** [comment]
Please check #6
